# Generated by Django 3.0 on 2019-12-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elephant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gorilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Monkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalStatus', models.CharField(default='COMPLETELY HEALTHY', max_length=32)),
                ('animalType', models.CharField(max_length=32)),
                ('healthPercentage', models.FloatField(default=100)),
                ('elephant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zoo.Elephant')),
                ('gorilla', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zoo.Gorilla')),
                ('monkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zoo.Monkey')),
            ],
        ),
    ]
