# Generated by Django 3.0 on 2019-12-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_auto_20191211_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
