# Generated by Django 3.0 on 2019-12-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_delete_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giraffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('animalStatus', models.CharField(default='COMPLETELY HEALTHY', max_length=32)),
                ('animalType', models.CharField(default='Giraffe', max_length=32)),
                ('healthPercentage', models.FloatField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Gorilla',
        ),
    ]
